@hostname = http://localhost:8100

get {{hostname}}/api/company/simplecompany/4286

###

get {{hostname}}/api/existing/parkerprofile/1400

### 

get {{hostname}}/api/promotion/allpromotions

### 

get {{hostname}}/api/company/allrates/4286

### 

post {{hostname}}/api/promotion/addpromotion
Content-Type: application/json 

{
   "PromotionId":0,
   "LotNumber": "3250",
   "PromotionName":"Carne Asada Taco",
   "StartDate":"2021-06-01",
   "EndDate":"2021-12-31",
   "CreatedBy":"coson",
   "DateEntered":"2021-11-27T21:54:33.097"
}

###

delete {{hostname}}/api/promotion/deletepromotion
Content-Type: application/json

{
   "PromotionId":838,
   "PromotionName":"Friday Special",
   "StartDate":"2021-06-01T00:00:00",
   "EndDate":"2021-08-31T00:00:00",
   "CreatedBy":"coson",
   "DateEntered":"2021-09-28T20:28:53"
}

###


get {{hostname}}/api/existing/simpleparker/09262019223738938002

###

get {{hostname}}/api/existing/parkerprofile/3250

### 
post {{hostname}}/api/existing/insertData
Content-Type: application/json

{
    "cityId": 0,
    "name": "Houston",
    "state": "TX",
    "population": "2215904"
}

###

get {{hostname}}/api/state/getallstates

###

get {{hostname}}/api/state/getstate/VI

###

post {{hostname}}/api/state/addstate 
Content-Type: application/json

{
	"stateName": "Puerto Rico",
	"abbreviation": "PR",
	"capital": "San Juan",
	"population": 4028977,
	"area": 99304,
	"dateEntered": "1979-02-14T00:00:00",
	"dateRank": 51
}

###

delete {{hostname}}/api/state/deletestate/VI

###

post {{hostname}}/api/state/addstate
Content-Type: application/json

{
  "stateName": "Virgin Islands",
  "abbreviation": "VI",
  "capital": "Charlotte Amalie",
  "population": 106631,
  "area": 346,
  "dateEntered": "2021-09-07T12:52:23.9195459-07:00",
  "dateRank": 53
}

###
post {{hostname}}/api/company/addnewcompany
Content-Type: application/json

{
  "lotNumber": "4286",
  "companyId": "01182022124120164253",
  "companyName": "Arcturus Technologies",
  "address": "904 S. Market",
  "addressLine": "",
  "city": "San Francisco",
  "state": "CA",
  "zipCode": "94117",
  "phone": "4153984123",
  "contact": "",
  "emailAddress": "testdata@gmail.com",
  "deliveryType": "Print",
  "active": "A",
  "startDate": "2022-01-05T00:00:00"
}